---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "fredonet.net"
subtitle: "My HomeLab"
logo: "assets/alf.png"
#icon: "fas fa-network-wired" # Optional icon

header: true
#footer: false
footer: '<a href="http://homer.fredonet.net">Alf`s Homelab</a>' # set false if you want to hide it.
columns: "4"


# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
#   url: https://b4bz.io
#  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#  title: "Demo !"
#  icon: "fa fa-grin"
#  content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Youtube"
    icon: "fab fa-youtube"
    url: "https://youtube.com" 
    target: "_blank"
  - name: "Wikipedia"
    icon: "fab fa-wikipedia-w"
    url: "https://www.wikipedia.org/"
    target: "_blank"
  - name: "Google"
    icon: "fab fa-google"
    url: "https://google.com"
    target: "_blank"
#  - name: "MS Office 365"
#    icon: "fab fa-windows"
#    url: "https://office.com"
#    target: "_blank"
  - name: "Amazon"
    icon: "fab fa-amazon"
    url: "https://amazon.de"
    target: "_blank"
  - name: "WhatsApp"
    icon: "fab fa-whatsapp"
    url: "https://web.whatsapp.com/"
    target: "_blank" 
  - name: "another page!"
    icon: "fas fa-file-alt"
    url: "#additionnal-page"
    target: "_blank"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Trastos"
    icon: "fas fa-cloud"
    items:
      - name: "Proxmox"
        logo: "assets/proxmox.png"
        subtitle: "Virtualization"
        tag: "Virtualization"
        url: "https://pvm.fredonet.net"
        target: "_blank" # optional html a tag target attribute
      - name: "Proxmox Backup Server"
        logo: "assets/proxmox.png"
        subtitle: "Virtualization"
        tag: "Virtualization"
        url: "https://pbs.fredonet.net"
        target: "_blank" # optional html a tag target attribute
      - name: "Synology"
        logo: "assets/synology.png"
        subtitle: "Mis cosas"
        tag: "NAS"
        url: "https://synology.fredonet.net"
        target: "_blank"
      - name: "Synology-Vizuete"
        logo: "assets/synology.png"
        subtitle: "Fuente inagotable de peliculas"
        tag: "NAS"
        url: "http://vizuete.es"
        target: "_blank"
#      - name: "Netgear AX1800"
#        logo: "assets/netgear.png"
#        subtitle: "Network Accesspoint"
#        tag: "Networking"
#        url: "https://access-point.fredonet.eu"
#        target: "_blank"
#      - name: "Netgear Switch"
#        logo: "assets/netgear.png"
#        subtitle: "Network Switch"
#        tag: "Networking"
#        url: "http://192.168.185.63"
#        target: "_blank"
  - name: "Routers y Net"
    icon: "fas fa-network-wired"
    items:
      - name: "Mikrotik"
        logo: "assets/mikrotik.png"
        subtitle: "firewall"
        tag: "Networking"
        url: "https://myfw.fredonet.net"
        target: "_blank"
      - name: "FritzBox"
        logo: "assets/fritz.png"
        subtitle: "El router"
        tag: "Conectividad"
        url: "https://4mmtc7jzxya85if1.myfritz.net:46754"
        target: "_blank"
      - name: "FritzBox Repeater 1200AX"
        logo: "assets/fritz.png"
        subtitle: "El repetidor 1"
        tag: "Conectividad"
        url: "https://1200ax.fredonet.net"
        target: "_blank"
      - name: "FritzBox Repeater 600"
        logo: "assets/fritz.png"
        subtitle: "El repetidor 2"
        tag: "Conectividad"
        url: "https://600rep.fredonet.net"
        target: "_blank"
      - name: "GL.iNet"
        logo: "assets/glinet.jpg"
        subtitle: "Router Madre"
        tag: "Connectividad"
        url: "https://glinet.fredonet.net"
        target: "_blank"
      - name: "TP Link TL-SG108E"
        logo: "assets/tplink.png"
        subtitle: "Network switch"
        tag: "Networking"
        url: "http://tl-sg108e.fredonet.eu"
        target: "_blank"
  - name: "Herramientas"
    icon: "fas fa-tools"
    items:
      - name: "Home Assistant"
        logo: "assets/ha.png"
        subtitle: "Goldäcker"
        tag: "Home Automation"
        url: "https://ha.fredonet.net"
        target: "_blank"
      - name: "Nodered"
        logo: "assets/nodered.png"
        subtitle: "Workflow"
        tag: "Home Automation"
        url: "https://nodered.fredonet.net"
        target: "_blank"
 #     - name: "pfSense"
 #       logo: "assets/pfsense.png"
 #       subtitle: "Firewall"
 #       tag: "Networking"
 #       url: "https://pfsense.fredonet.net:5443"
 #       target: "_blank"
      - name: "portainer"
        logo: "assets/portainer.png"
        subtitle: "docker"
        tag: "Servers"
        url: "https://portainer.fredonet.net"
        target: "_blank"
      - name: "pihole"
        logo: "assets/pihole.png"
        subtitle: "DNS"
        tag: "Networking"
        url: "https://pihole.fredonet.net/admin"
        target: "_blank"
 #     - name: "pihole2"
 #       logo: "assets/pihole.png"
 #       subtitle: "DNS"
 #       tag: "Networking"
 #       url: "https://pihole2.fredonet.eu/admin"
 #       target: "_blank"
      - name: "apcupsd Server"
        logo: "assets/nut.png"
        subtitle: "UPS"
        tag: "UPS"
        url: "http://nut.fredonet.net/cgi-bin/apcupsd/multimon.cgi"
        target: "_blank"
 #     - name: "Chrome System Monitor"
 #       logo: "assets/kasm.png"
 #       subtitle: "Chrome"
 #       tag: "Monitoring"
 #       url: "chrome://sys-internals/#"
 #       target: "_blank"
#      - name: "PHPMyAdmin"
#        logo: "assets/phpmyadmin.png"
#        subtitle: "DataBases"
#        tag: "Remote"
#        url: "https://pma.fredonet.net"
#        target: "_blank"
#      - name: "influxDB"
#        logo: "assets/influxdb.png"
#        subtitle: "DataBases"
#        tag: "Monitoring"
#        url: "http://influxdb.fredonet.eu"
#        target: "_blank"
#      - name: "Grafana"
#        logo: "assets/grafana.png"
#        subtitle: "Monitorización"
#        tag: "Monitoring"
#        url: "https://grafana.fredonet.eu"
#        target: "_blank"

  - name: "Aplicaciones"
    icon: "fas fa-user-secret"
    items:
      - name: "bitwarden"
        logo: "assets/bitwarden.png"
        subtitle: "seguridad"
        tag: "passwords"
        url: "http://vault.bitwarden.com"
        target: "_blank"
      - name: "github" 
        logo: "assets/github.png" 
        subtitle: "Repository" 
        tag: "develpment" 
        url: "https://github.com/"
        target: "_blank"
      - name: "OVH"
        logo: "assets/ovh.png"
        subtitle: "DNS & Mail"
        tag: "productivity"
        url: "https://ovh.com"
        target: "_blank"
      - name: "cloudflare" 
        logo: "assets/cloudflare.png" 
        subtitle: "DNS" 
        tag: "productivity" 
        url: "https://www.cloudflare.com/de-de/"
        target: "_blank"
      - name: "icloud" 
        logo: "assets/icloud.png" 
        subtitle: "Apple" 
        tag: "productivity" 
        url: "https://www.icloud.com/"
        target: "_blank"
      - name: "MS Office 365" 
        logo: "assets/office.png" 
        subtitle: "Microsoft" 
        tag: "productivity" 
        url: "https://www.office.com/"
        target: "_blank"
#  - name: "eMails"
#    icon: "fas fa-mail-bulk"
#    items:
      - name: "Office 365 Mail"
        logo: "assets/outlook.png"
        subtitle: "alfredogarciahernanz@live.de"
        tag: "eMail"
        url: "https://outlook.live.com/mail/0/"
      - name: "OVH Mal"
        logo: "assets/ovh.png"
        subtitle: "alfredogarciahernanz@fredonet.eu"
        tag: "eMail"
        url: "https://pro2.mail.ovh.net/"
      - name: "iCloud Mail"
        logo: "assets/icloudm.png"
        subtitle: "alfredogarciahernanz@icloud.com"
        tag: "eMail"
        url: "https://www.icloud.com/mail/"
      - name: "GMail"
        logo: "assets/gmail.png"
        subtitle: "alfredogarciahernanz@gmail.com"
        tag: "eMail"
        url: "https://mail.google.com/mail/u/0/#inbox"
